function AboutPage() {
  return (
    <div className = "text-center p-10">
        <h1 className = "text-3xl font-bold my-4">About</h1>
        <p className = "text-gray-300">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam soluta iste numquam quam corrupti adipisci consequatur voluptatem explicabo praesentium velit laborum repellendus facere quidem, ipsum iusto exercitationem error esse ut accusamus eos quis suscipit vero. Cumque assumenda aut aspernatur natus? Voluptate nisi quos adipisci accusamus blanditiis. Deserunt rerum odio sapiente! Quo, sequi! Voluptatibus quos aliquid laudantium quae totam magni aspernatur aperiam accusantium quo. Ipsam ex tempora illo dolore, earum alias quis totam quos, animi eius omnis, facilis hic accusamus optio inventore doloribus aspernatur eaque modi quasi reprehenderit rerum sit eos harum! Tempore est, nulla corporis ut rerum hic, cupiditate facere illo ad delectus reprehenderit inventore, quo laudantium ullam officia sapiente dolorem molestias quos eveniet consequuntur incidunt at explicabo blanditiis recusandae? Voluptas, vitae. Eius, harum. Suscipit facere maxime reiciendis, ipsam beatae dolor commodi. Recusandae accusantium eveniet, excepturi, numquam, magni quasi animi quas nostrum fugit non quidem laborum porro asperiores optio vitae voluptatem explicabo! Accusantium sint sequi nesciunt officiis? Inventore quas illum tempore autem maxime tempora totam sunt perferendis fuga, velit, neque libero fugit minima atque cum quidem, unde temporibus sint pariatur laboriosam voluptas officia nisi rem. Ipsum, neque. A eaque nihil nobis natus ipsum ut commodi soluta ad ipsa? Reiciendis voluptatem maiores rerum officiis sapiente consequuntur dignissimos pariatur doloribus sint, distinctio, aspernatur, cumque tenetur dolor a totam aliquam iste! Nulla vero tempora quos! Voluptatum nam ratione maxime commodi voluptatem mollitia recusandae quia, tempore unde, nobis a blanditiis itaque, magnam voluptate ab laudantium laborum temporibus? Architecto, earum ipsa? Vero dolor quam consectetur labore eligendi amet nobis dicta. Quae voluptas rem enim tempora in, minima at eum ratione dolores id non magni veniam dolor, maxime, quod sint! Expedita corrupti reprehenderit eum tenetur et, officiis recusandae necessitatibus maiores. Cupiditate, blanditiis. Ipsum officiis suscipit atque porro est id exercitationem voluptatibus! Cum deserunt fugit at inventore?</p>
    </div>
  )
}

export default AboutPage